local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: 2b038bb2775a0533be007c8a662c09311921a168efb337383d656e337d1b83c9
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
