local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: e36d89e66cfb2d7f18d9dde3db781df5feaf6e2acbaa447118ff3c05848d33cb
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
