local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: 20195621797386fd909c53f516c2a81236876cf36231892c7b4f8b0b9e1ba776
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
