local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: 3eb8e5b389134131c24d7ed6efc17417f5fad874240cce33b47d2ae867b03368
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
