local_resinos:
  app-name: local-app
  build-triggers:
    - Dockerfile: 224f4ca221ee8091c5a91bab1d8d4e0680bbcfb8575db12950ab75846ba042ee
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
